### ISSUE TITLE
create repository for read challenge

### ISSUE THREAD

**Issue by Bantolomeus** [Bantolomeus/bookmaster4000mkii#13]
- [x] save function to save data in challenge.json
- [x] update function
- [x] read function

**Comment by Bantolomeus** [comment]
I go with one function for save and update, because they do the same

**Comment by Bantolomeus** [comment]
@Husterknupp rdy for review

**Comment by Husterknupp** [comment]
please use imperative language in your commit messages. It's shorter and it reads better.

See https://gist.github.com/stephenparish/9941e89d80e2bc58a153#message-body

**Comment by Husterknupp** [comment]
all commits look good 👍
