### ISSUE TITLE
sum up same update dates on get endpoint response

### ISSUE THREAD

**Issue by Bantolomeus** [Bantolomeus/bookmaster4000mkii#16]
- [x] if there exist multiple updates for a book on one day sum up pagesRead of the day and return only one entry for the day with the sum on pagesRead
- [x] use filter and getOrElse with fixed filter

**Comment by Bantolomeus** [comment]
@Husterknupp pls review

**Comment by Husterknupp** [comment]
@Bantolomeus please answer my comments on b6febad

**Comment by Bantolomeus** [comment]
@Husterknupp rdy for rereview

**Comment by Bantolomeus** [comment]
@Husterknupp  rdy for rereview

**Comment by Bantolomeus** [comment]
WOW the filter and .getOrElse function made something, but not what I wanted. With it I got the wrong data, with my function I get the right data. Build it back.

**Comment by Husterknupp** [comment]
dude, it would really help me, like I tried to express in the other ticket, if you would put in the issue description what to test. To test the functionality, I need to know, after I start the application, what should happen?

Supposing you're talking about the `PUT /books` endpoint I tried to do this 
```
curl -X PUT http://localhost:8080/books/update -d '{"name": "bible", "currentPage": 2, "date": "2018-02-12 18:53:00"}' -H "Content-Type: application/json"
```

but failed
```
{"timestamp":1518459134477,"status":500,"error":"Internal Server Error","exception":"java.text.ParseException","message":"Unparseable date: \"\"","path":"/books/update"}
```
-> I guess because `ChallengeService` on line 19 expects a challenges object to exist. But initially I don't have one.

----

Also the `updateBook` methods doesn't make a lot of sense to me
1. because I don't understand why both, the book and the challenge gets updated (shouldn't the endpoint be on the challenges controller?)
2. because the naming is kacke. Per convention the naming is `PUT /$resourceName/$id` to update a single entity of your collection/resource or `POST /$resourceName` to create a new entity (response body should contain the id then)

---

other than that, please document the
 - [ ] document the date format that needs to be used in the PUT/POST endpoints

**Comment by Bantolomeus** [comment]
@Husterknupp excuse me the missing information for testing. I asked you at the beginning what you whant to do and you sad code review and no testing. 
I will add more description for testing in the upcoming tasks, but not in the currently existing ones.
If you want to know how a file will be populated you can always look in the DTOs. An example for challenge file: `{
    "pagesPerDay": 50,
    "pagesSurplus": 13,
    "startPagesSurplus": 90,
    "pagesSinceStart": 422,
    "pagesEverRead": 1504,
    "dateStarted": "01/02/2018"
}`
And yes, I excluded the check for a existing file on purpose as described in the corresponding ticket. You can create this file manually in your root project folder, the same goes for booksUpdate and books file, if it is not possible otherwise.

> because I don't understand why both, the book and the challenge gets updated (shouldn't the endpoint be on the challenges controller?)
I was not sure how I want to do this. I saw two options, the way I do it now, which is the easier one or I will update the challenge file during the get call from the challenge controller, which needs more variables in the challenge file and in the booksUpdate file. Right now the challenge gets updated on a book update, which is logically seen the right choice, because the challenge depends on the book updates and if I read 10 pages and update this, then should also the challenge be updated.
The primary goal is to read, thats why I move the books and booksUpdate file in the middle. To help me achieve my goal of reading I have my challange system, that tracks changes during the process of reading and gets updated on changes.
Does it help you to understand why the book update also updates the challenge?

> because the naming is kacke. Per convention the naming is PUT /$resourceName/$id to update a single entity of your collection/resource or POST /$resourceName to create a new entity (response body should contain the id then)
I am sorry that the naming is kacke. But by the way of the convention it is just not usable for me.
See, I am a human and I know the title of my book or books that I read. If I want to update one of my 5 currently reading books, I do not want to do a get request to get a id which I need to update the book. I want to directly update my book with its book title as identifier. That is one less step in the process, and exactly what I want.
If I am brave and motivated enough to implement a front end with wadin or angular, then I will refactor this and use ids as identifier and use the endpoints as you pointed it out. Right now this would make this more complicated and I build this for me and not other people. If other people want to use it for there needs they are free to adjust the code to there needs.
Does that clearify your questions?

**Comment by Bantolomeus** [comment]
put body:
`{
"name":"mein Buch",
"currentPage":219
}`

post body:
`{"name":"book name",
  "author":"author name",
  "pagesTotal":549
}`

**Comment by Husterknupp** [comment]
> you sad code review and no testing

Touché. I agreed on only doing code review. Somehow felt strange though to ignore what the feature is doing. Will do only code review now unless we change the agreement.

> Does it help you to understand why the book update also updates the challenge?

Not really. I know this is about reading books and not doing sport exercises. But within this context, this app is less about cataloging books, but rather about your challenge reading them. What you're changing with every PUT is how far you've come in your challenge, not how much the book changed. But this is pretty much opinion. So do whatever feels more natural for yourself.

> directly update my book with its book title as identifier

I think I didn't make my point clear. My problem is not about the id (which btw translates to **id**entifier and could as well be a book's name). It's about the path suffix */update* which is bad.

* GET /books
* POST /books
* PUT /books/$name

I would expect

**Comment by Husterknupp** [comment]
But if I understand correctly, what you wanna do with the PUT, is save a new "reading progress". So why not naming it so? 

`POST /books/$name/readingProgress`

**Comment by Husterknupp** [comment]
You could avoid that with a) posting on a dedicated endpoint `POST /bookUpdates` which takes as an input the same bookUpdate payload as you have now. Or by b) still doing `PUT /books/$name`, but not sending the bookName in the payload, but rather using in the controller the $name url param

**Comment by Husterknupp** [comment]
please respond to my comments on a0b4b56 .. and let's bring this to an end. It's a rather big issue, dude :)

**Comment by Bantolomeus** [comment]
implemented all code comments

**Comment by Bantolomeus** [comment]
@Husterknupp ready for review

**Comment by Husterknupp** [comment]
Approved 👍
