### ISSUE TITLE
create function for summed pages over all books in challenge service

### ISSUE THREAD

**Issue by Bantolomeus** [Bantolomeus/bookmaster4000mkii#18]
- [x] sum up all current pages of all books in the getChallengeData function in challenge service

**Comment by Bantolomeus** [comment]
Well, I did it with `val pages = bookRepository.getBooks()?.books?.sumBy { it.currentPage!!.toInt() }
            challengeService.savePagesEverRead(pages?.toLong())`
but since I needed it only once I decided to not commit it

**Comment by Bantolomeus** [comment]
and it would be overhead to calculate the pagesEverRead every time anew on the get call, so it is saved in the challenge file. With this the scope of this issue is only calculate initiate pagesEverRead value and that happened.

**Comment by Bantolomeus** [comment]
@Husterknupp rdy for review

**Comment by Husterknupp** [comment]
cannot find any commit to review.
Approved 👍
