### ISSUE TITLE
create endpoint for challenge

### ISSUE THREAD

**Issue by Bantolomeus** [Bantolomeus/bookmaster4000mkii#20]
- [x] create new request mapping/challenge 
- [x] create get endpoint to receive current pages plus/minus of read challenge and total pages read over all books 
- [x] create DTO for getChallengeData
- [x] change return value of getChallengeData to correct DTO

**Comment by Bantolomeus** [comment]
@Husterknupp rdy for review

**Comment by Husterknupp** [comment]
please react on my comment on 864430567acc76057984a15a16f9220c053be733 before I close this

**Comment by Bantolomeus** [comment]
refactored according to your comments
