### ISSUE TITLE
read challenge file

### ISSUE THREAD

**Issue by Bantolomeus** [Bantolomeus/bookmaster4000mkii#22]
- [x] name file challenge
- [x] save dateStarted, pagesStarted, currentPages, pagesPerDay, pagesEverRead
- [x] create DTO for the file

**Comment by Bantolomeus** [comment]
@Husterknupp pls review

**Comment by Husterknupp** [comment]
@Bantolomeus please guide me here, I don't know from the description what needs to be done

**Comment by Bantolomeus** [comment]
@Husterknupp I will safe all the relevant data regarding the read challenge into this file. Therefore I wrote down the needed fields and the file name and to create a dto to work with the file.
Do you need more explanation?

**Comment by Husterknupp** [comment]
Yes I need more. Sorry if I wasn’t clear enough. If I would be a tester, I need the GIVEN WHEN THEN. At least for this one. Can’t figure out myself.

Am 07.02.2018 um 19:54 schrieb Christian Bantel <notifications@github.com<mailto:notifications@github.com>>:


Assigned #22<https://github.com/Bantolomeus/bookmaster4000mkii/issues/22> to @Husterknupp<https://github.com/husterknupp>.

**Comment by Bantolomeus** [comment]
given: nothing
when task complete: a dto with the fields: dateStarted, pagesStarted, currentPages, pagesPerDay, pagesEverRead and a file called challenge with the same fields
then: it should work with given challenge logic, which is right now not finished

I have the feeling this will also not help you, but I really do not know how to explain it in more depth, because there is no more to it. You could also see this issue as, how will I populate my future file for the challenge and create a dto accordingly.

**Comment by Bantolomeus** [comment]
Ah well, and the application shall be able to read the defined file

**Comment by Bantolomeus** [comment]
added another field to the challengeDTO
@Husterknupp ready for update
