### ISSUE TITLE
create readme

### ISSUE THREAD

**Issue by Bantolomeus** [Bantolomeus/bookmaster4000mkii#25]
- [x] write a short description of this project in the reamde
- [x] add a gif/meme

**Comment by Husterknupp** [comment]
I would like to take over. Since I have this very important badge to add anyways

**Comment by Bantolomeus** [comment]
Go ahead

**Comment by Husterknupp** [comment]
quick response.. cool :) Please find the current version here
https://github.com/Bantolomeus/bookmaster4000mkii/blob/master/README.md

@Bantolomeus in the README, the base url for api calls missing as well as a proper licence. Can you please add this?

**Comment by Husterknupp** [comment]
and I will treat the super cool and important badge as a gif/meme, oK? It makes the readme so colorful :-D

**Comment by Bantolomeus** [comment]
- Badge: awesome
- base url was correct, I removed the question marks
- I added a license file and wrote the license in the README

**Comment by Husterknupp** [comment]
👍
