### ISSUE TITLE
update goes wrong

### ISSUE THREAD

**Issue by Bantolomeus** [Bantolomeus/bookmaster4000mkii#30]
update file: 
Has at least two updates from today and your current update was not the last one.

If you update your book you will will get a wrong pagesRead in the update because the last update in the update file is picked and not the one which you want to update and have already updated today.

- [x] adjust filter to get the correct update

**Comment by Bantolomeus** [comment]
@Husterknupp ready to review

**Comment by Husterknupp** [comment]
Approved 👍(anyway the code has changed already since e99d12b)
