### ISSUE TITLE
write tests for bookService

### ISSUE THREAD

**Issue by Bantolomeus** [Bantolomeus/bookmaster4000mkii#34]
I want tests for all use cases to see breaking functionality on changes and future implementations.
That needs adjustments in the code itself.

- [x] create test for getBook with book name
- [x] create test for getBook without data
- [x] create test for getAllBooks with books
- [x] create test for getAllBooks without books
- [x] create test for createBook without current Page
- [x] create test for createBook without payload
- [x] create test for createBook with partial payload
- [x] create test for updateBook with valid request body

**Comment by Husterknupp** [comment]
maybe some integration line tests would be cool. Wramp up the container, fire rest calls. Rest assured. But it should happen only for major use cases I think 🤔

Am 20.02.2018 um 15:15 schrieb Christian Bantel <notifications@github.com<mailto:notifications@github.com>>:


I want tests for all use cases to see breaking functionality on changes and future implementations.
That needs adjustments in the code itself.

  *    make code testable
  *    create test for getBook with book name
  *    create test for getBook with not existing book name
  *    create test for getBook without parameter
  *    create test for createBook with valid request body
  *    create test for createBook with invalid request body
  *    create test for updateBook with valid request body
  *    create test for updateBook with invalid request body

**Comment by Bantolomeus** [comment]
Sounds good, the minor- and edge cases can be handled in unit tests

**Comment by Bantolomeus** [comment]
I will write Unit tests first and create integration tests afterwards. I want to have tests, it is hilarious to test everything manually all the time.
