### ISSUE TITLE
update on non existing book

### ISSUE THREAD

**Issue by Bantolomeus** [Bantolomeus/bookmaster4000mkii#37]
If you update a non existing book, the update is written into booksUpdates.

- [x] check if book exists before writing into booksUpdates

**Comment by Bantolomeus** [comment]
@Husterknupp ready for review

**Comment by Husterknupp** [comment]
Approved 👍 Wondering why u're creating a ticket with all that labeling mumbo jumbo for only one single "4 additions and 4 deletions" commit. Why not simply fixing it right along the way?
