### ISSUE TITLE
refactor BookController

### ISSUE THREAD

**Issue by Bantolomeus** [Bantolomeus/bookmaster4000mkii#38]
- [x] create separate endpoint to return all books
- [x] rename pathVariable id to name

**Comment by Bantolomeus** [comment]
@Husterknupp ready for review

**Comment by Bantolomeus** [comment]
As we discussed, thats how our endpoints should look and like they are since the last commit:
GET /books
GET /books/$id
POST /books

how should be the PUT endpoint?
Put /books/$id   ?

**Comment by Bantolomeus** [comment]
@Husterknupp ready for review

**Comment by Husterknupp** [comment]
good guess señor

PUT /books/$id

**Comment by Bantolomeus** [comment]
ready for review

**Comment by Husterknupp** [comment]
Will close this now after reviewing all. Thanks for reviewing my commit on the spot. Thanks nice. kbye
