### ISSUE TITLE
upload test files

### ISSUE THREAD

**Issue by Bantolomeus** [Bantolomeus/bookmaster4000mkii#43]
- [ ] upload the json files with a few data to test the program asap after checking it out

**Comment by Bantolomeus** [comment]
@Husterknupp I added the three needed files for testing the application, maybe you want to try it out?

**Comment by Husterknupp** [comment]
yes I would like to try it out. But a README would be nice. A README with the port and base url so that I know where to put the endpoints I find in the controllers.

**Comment by Bantolomeus** [comment]
I will write this information into the readme.

**Comment by Husterknupp** [comment]
please do this along with #25

**Comment by Bantolomeus** [comment]
You already figured it out yourself. Do you need any more information? If not close this issue, please.

**Comment by Bantolomeus** [comment]
@Husterknupp do you need more information? If not close the issue, please.

**Comment by Husterknupp** [comment]
no, I could run the app and also use the sample files you provided 👍 I even created a book myself and found it serialized in the `books.json`
