### ISSUE TITLE
Travis setup

### ISSUE THREAD

**Issue by Bantolomeus** [Bantolomeus/bookmaster4000mkii#44]
- [x] configure travis ci for the project
- [x] run maven ~~+ UI tests~~ (#95)
- [x] add Embedding Status Images to the readme
- [x] create a working pipeline for commits on master branch
- [x] remove Husterknupps badge from the readme

**Comment by Bantolomeus** [comment]
Removing the birthday badge from the readme is prohibited until all other tasks in this ticket are completed.
Badge is shown in #45

**Comment by Husterknupp** [comment]
voting for this to avoid problems like #90

**Comment by Bantolomeus** [comment]
Yes, I want to do this issue right update of desktop version.

**Comment by Bantolomeus** [comment]
Well, for now there are no frontend tests, or ui or E2E tests. I would prefer to set them up in another issue and then as part of the ticket to add them to the travis runs. 
@Husterknupp do you agree?

**Comment by Husterknupp** [comment]
ok makes sense. Can you have a look in the repo settings, please.. I think it should be possible to prevent PR merges in case Travis CI runs fail. Can ... this is what we just discussed  📞

Am 14.11.2018 um 21:25 schrieb Christian Bantel <notifications@github.com<mailto:notifications@github.com>>:


Assigned #44<https://github.com/Bantolomeus/bookmaster4000mkii/issues/44> to @Husterknupp<https://github.com/Husterknupp>.

**Comment by Bantolomeus** [comment]
I added the cache, I did not read about it, I stoped after it worked =D
