### ISSUE TITLE
Travis Embedding Status Images

### ISSUE THREAD

**Issue by Bantolomeus** [Bantolomeus/bookmaster4000mkii#45]
- [ ] add the Travis Embedding Status Images to the readme

**Comment by Husterknupp** [comment]
why is this one so important that there's a dedicated milestone? I don't see any meaningful unit tests or would you like to deploy the app somewhere?

If you simply wanna have a badge in your README (_that's still missing btw_ 🙈), we can use this one
![image](https://user-images.githubusercontent.com/1265382/40448070-b9726dbc-5ed4-11e8-8fcf-fe2139fac929.png)

**Comment by Bantolomeus** [comment]
closed because it is a duplicate of #44 
Nevertheless, @Husterknupp add the badge in the readme!

**Comment by Husterknupp** [comment]
did it in #25
