### ISSUE TITLE
refactor put endpoint in book controller

### ISSUE THREAD

**Issue by Bantolomeus** [Bantolomeus/bookmaster4000mkii#51]
As a ~~bookmaster4000mkii user~~ bookmaster I want to update my reading stand easily, to not waste time.

Right now one has to define the book name as path variable and in the payload also stands the book name.
- [x] Find out if it is possible to remove the book from the path or from the payload
- [x] Figure out which approach follows the rest convention, book name as path variable or in the payload
- [x] Change rest endpoint according to convention
- [x] Change the underlying code

**Comment by Husterknupp** [comment]
keeping the book name in the path would make access logs more meaningful since they’re not recording the payload. Also 

PUT resource/$resourceId is the convention IIRC

**Comment by Bantolomeus** [comment]
That is the same I remember and I looked it up and [here](https://spring.io/understanding/REST) is a very short summary.

**Comment by Husterknupp** [comment]
please see my comments and close this if all is done.
