### ISSUE TITLE
Frontend MVP

### ISSUE THREAD

**Issue by Bantolomeus** [Bantolomeus/bookmaster4000mkii#54]
- [x] show the parts of the challengeDTO in the frontend (pagesPerDay and pagesAheadOfPlan)
- [x] #48 should be solved beforehand 
- [x] call the get endpoint https://github.com/Bantolomeus/bookmaster4000mkii/blob/c9847b79125c9a5d8fcf17add44ad15d5ff3aab9/src/main/kotlin/com/bantolomeus/controller/ChallengeController.kt#L14-L17 
for the needed informations 
- [ ] ~~@Husterknupp do we want an extra endpoint with only the two needed informations?~~

**Comment by Husterknupp** [comment]
@Bantolomeus please review, and merge to master once review is good

**Comment by Bantolomeus** [comment]
As mentioned in the comment in https://github.com/Bantolomeus/bookmaster4000mkii/commit/43999eb43613f1f424c6dc23b35826140aa52479 please change the title and then I will merge it into master.

**Comment by Husterknupp** [comment]
@Bantolomeus I changed the title accordingly. Please do the merge :)
