### ISSUE TITLE
Return saved book on update

### ISSUE THREAD

**Issue by Bantolomeus** [Bantolomeus/bookmaster4000mkii#55]
- [x] implement return value to updateBook
- [x] adjust tests

**Comment by Husterknupp** [comment]
I don’t see why you would need to mention the test in the description. Shouldn’t the change of a method signature anyways break existing tests of that method?

If so, a feature would not be complete unless everything is implemented and broken tests are fixed. Makes sense?

**Comment by Husterknupp** [comment]
👍 

@Bantolomeus just out of curiosity: why do all involved classes (controller, service, repository) return the updated book? As opposed to only the controller returning the book and the other classes being let unchanged..

**Comment by Bantolomeus** [comment]
@Husterknupp I do not fully get what you mean. If I understand you correctly I shall call the repository in the controller to get the book? I would not like that. I know I just drag the payload from the repository through the service back to the controller, but I do not see how to not do it that way and keep the code clean.

**Comment by Husterknupp** [comment]
> If I understand you correctly I shall call the repository in the controller to get the book

No that was not what I meant. You changed the signatures like this
* `ctrl. updateBook` -> `ctrl.updateBook : BooksUpdatesFileDTO` (which makes sense according to the idea of this ticket)
* `repo.saveBookUpdate` -> `repo. saveBookUpdate : BooksUpdatesFileDTO <- why a return type here?`
* `service.updateBook` -> `service.updateBook : BooksUpdatesFileDTO <- and here..?`

**Comment by Bantolomeus** [comment]
I does this so that I always know what kind of data I hold right now. If I only work with lists all the time until I am in the controller and do the transforming of the data in the controller, then in my opinion I would do something wrong, because I would not know what data exactly I am working with in a certain line of code. Well I could call a assembler class to put my data into a DTO.
I have to admit, that the DTO names are not that clear or intuitive. I hope they will get better after I separate book updates from book logic.

**Comment by Bantolomeus** [comment]
Please state another point of view, if you have an alternative way to deal with it.

**Comment by Husterknupp** [comment]
I find it rather hard to make my point clear. Let’s move the discussion to real life
