### ISSUE TITLE
Bootstrap UI

### ISSUE THREAD

**Issue by Husterknupp** [Bantolomeus/bookmaster4000mkii#63]
before we can work on #54 we need to also enter the javascript world.

* npm
* Webpack
* AngularJs
* put bundle.js in /public
* `mvn package` should include the `bundle.js && index.html` 
* and running the result jar should deliver index.html under `localhost:8080` and in the index.html the path to find the bundle.js path should be working
* development server with hot reload

**Comment by Husterknupp** [comment]
@Bantolomeus you need to do a few things to get npm up and running
1. `brew install nvm` (node version manager lets you update node versions later on easily)
2. `nvm install v8.11.4` (installs one of node's latest LTS versions)
3. `nvm use v8.11.4` (not sure if this is included in 2. already)

**Comment by Bantolomeus** [comment]
works for me 👍

**Comment by Husterknupp** [comment]
thanks @Bantolomeus for the rough review. At least it works not only on my machine ;-)
