### ISSUE TITLE
refactor challenge

### ISSUE THREAD

**Issue by Bantolomeus** [Bantolomeus/bookmaster4000mkii#66]
- [x] move challenge progress data `pagesAheadOfPlan, pagesSinceStart and pagesEverRead` out of the challengeDTO
- [x] reading state is calculated on `GET /progress` endpoint
- [x] save `pagesSinceStart and pagesEverRead` in progress.json
- [x] clean up the code mess
- [x] manually test functionality

**Comment by Bantolomeus** [comment]
This change will be a breaking change. 

- `startPagesAheadOfPlan` will be completely removed
- `pagesAheadOfPlan` is now called reading status
- reading status is now calculated on the specific endpoint `GET /progress`
- challengeDTO holds only `pagesPerDay` and `dateStarted`
- with all the changes the challenge plays a smaller role in the code and the progress gains attention

I work on feature/progress for this feature

**Comment by Husterknupp** [comment]
@Bantolomeus this is super tedious. For so many commits a seperate branch and PR is the only way I suggest. I created therefore a dedicated branch which should not be merged but can be used to do the review more condensed: #87

**Comment by Bantolomeus** [comment]
Yes, this is one ticket I had in mind when I suggested I should work in feature branches. Good thinking with #87

**Comment by Husterknupp** [comment]
as discussed.. let's review #87. I'll close this one anyway since the code is live
