### ISSUE TITLE
Save progress via Frontend

### ISSUE THREAD

**Issue by Bantolomeus** [Bantolomeus/bookmaster4000mkii#71]
- list books endpoint https://github.com/Bantolomeus/bookmaster4000mkii/blob/0b4c1f64c20a2697d50808fcbd41922410e7efb0/src/main/kotlin/com/bantolomeus/controller/BookController.kt#L18-L22
to save a update

User Story
- [x] get and list all books
- [x] (maybe filter by status unread)
- [x] display `currentPage`
- [x] provide input for `currentPage` + save
- [x] after save action either forward to progress page (Banto: I prefer that one) or show how much better the user did with the last action (Banto: you can also try this one if you like or better, give the user the choice what he wants to know)

- [ ] when done, close #75

**Comment by Husterknupp** [comment]
for navigation/routing use ui-router: https://ui-router.github.io/ng1/tutorial/helloworld

**Comment by Bantolomeus** [comment]
I commented the description

**Comment by Husterknupp** [comment]
you can see that there's progress on this one, just that I decided to upgrade also other UI dependencies, which needs a little bit Einarbeitungszeit. Only webpack css plugin left IIRC.

**Comment by Husterknupp** [comment]
@Bantolomeus would it make sense to change the above endpoint's signature so that not only book title (names) are returned but book content as well? This way I could show you the `pagesRead` immediately for instance on the list page...

**Comment by Bantolomeus** [comment]
@Husterknupp I would say no, it does not makes sense. I wanna split the logic and separat book and progress. If I return a book on a progress update it would fuck up the separation of book and progress.
Right now progress is called book update.

**Comment by Bantolomeus** [comment]
Nevermind, I just found out that I referenced the wrong endpoint to list all books for you.

**Comment by Bantolomeus** [comment]
I updated the description, now with the correct endpoint. OK, rethinking. Generally it would be ok to change the return value and enrich it. But right now I use it to see quick all book names. If we add more information there I will not see all the books so easily in the response. This would be resolved if the frontend has reached a certain point. 
Deal: 
I will write another endpoint for me that does what the old one did and enrich the existing one for you.
If you are cool with this I would like to know what you wand as return value. A list of all books? List<bookDTO> ? That may be the cleanest way and that way the endpoint can be used for other frontend calls related to books.

**Comment by Bantolomeus** [comment]
Why... You wanna save via frontend, so the endpoint was correct.... and then we are back to square one. 


> I would say no, it does not makes sense. I wanna split the logic and separat book and progress. If I return a book on a progress update it would fuck up the separation of book and progress.
> Right now progress is called book update.

Long story short, this is my answer.

**Comment by Bantolomeus** [comment]
Updated description.

**Comment by Husterknupp** [comment]
Nice conversation you were having with yourself ^^

 correct me if I’m wrong but the books also contain meta data that’s not related to any progress, such as title and pages total for instance. But I agree that it would not be clever to combine progress and books.

To get what i want (pages left to read for book A) what would I need to query? Or maybe that’ll gonna be a separate user story, what do you think?

**Comment by Husterknupp** [comment]
<img width="1680" alt="screen shot 2018-10-30 at 08 58 25" src="https://user-images.githubusercontent.com/1265382/47703910-112d9980-dc22-11e8-8cc3-a9e5f9d62b25.PNG">

@Bantolomeus what do you think of this? The input is shown `on-mouseover` and is focused automagically. So there's no click needed to input the pages, only hover over the book that you read today.

Todo is still 
* the actual saving call
* some user feedback on the overall progress after input (not sure how to send you to the overview page.. seems a bit bad UX to hard switch the page after the input)
* cleanup css

**Comment by Bantolomeus** [comment]
> correct me if I’m wrong but the books also contain meta data that’s not related to any progress, such as title and pages total for instance.
That is correct.

> To get what i want (pages left to read for book A) what would I need to query? Or maybe that’ll gonna be a separate user story, what do you think?
Right now there is not endpoint to get this specific data. I would create a separat issue. I would implement GET books/{bookID}/pagesLeft   bookID is the book name. Created Issue #80

> @Bantolomeus what do you think of this? The input is shown on-mouseover and is focused automagically. So there's no click needed to input the pages, only hover over the book that you read today.
There are two books on the shown page? And you hovered over the right one? We can go with this. 👍 

Question: Are there all books shown? I hope not, I hope only books that are not finished. Do you wanna keep #36 into mind? I do not know if this would interfere with this issue here, because I do not know how I wanna add this future list. Forget #36 for this issue here =)

**Comment by Husterknupp** [comment]
maybe don’t create too many endpoints now but first have a look yourself, test the UI and tell me what’s missing (everything described in the ticket is done I think). 

To only show not yet finished books (is this described in the ticket?) can you please provide me a query parameter on the GET /books endpoint? i find it irritating to get all, display for a moment all only to remove a few from the UI again after the second call finished. My 2 cents

**Comment by Husterknupp** [comment]
@Bantolomeus features are ready. I'd like to clean up the code. Please wait with the review until the pull request. This will speed up reviewing alot.

And btw, would you like to get a rough intro on how html and javascript works together the AngularJs way? Or should I wait for your questions?

**Comment by Bantolomeus** [comment]
@Husterknupp I choose the intro.
You want a query param to show only books that are not finished? Something like GET /books?progress=inProgress and progress can be inProgress, noProgress (future books), done.

**Comment by Husterknupp** [comment]
exactly that's what I was talking about. I see you created #81 for this. Maybe the statuses should not be exclusive, so querying for
* `?progress=inProgress` should be possible as well as
* `?progress=noProgress,done` which should return the combined set of both statuses

**Comment by Husterknupp** [comment]
done, but will still incorporate #80

**Comment by Husterknupp** [comment]
reviewed it #85
