### ISSUE TITLE
Change GET /books endpoint

### ISSUE THREAD

**Issue by Bantolomeus** [Bantolomeus/bookmaster4000mkii#79]
- [x] return `List<BookDTO>`
- [x] use a list instead of mutable list

**Comment by Husterknupp** [comment]
is this still relevant after the discussion in #71 ?

If so, wouldn’t it make sense to keep one endpoint, not create s second one for the same entity, but rather to allow specifying the fields that should be shown in the response?

so `GET /books?fields=name`

would return
`[{name: „Rumo“}, {name: „Warcraft“}]`

**Comment by Bantolomeus** [comment]
No, I want a list of book names, not a list of map. Later in the progress of the application the GET /books/names endpoint can be deleted, but right now I want it this way because I look at the response and I want to see the needed informations and nothing more and that are only the book names in this case.
Yes it is still relevant, because this issue here contains the doing to change the GET /books endpoint as it stays in the summary/title.

**Comment by Bantolomeus** [comment]
Has to be done before #81

**Comment by Bantolomeus** [comment]
Now that we have the frontend MVP I no longer need the list of the books. The frontend does not contain a list of all books, but all books that are not finished is enough right now.

**Comment by Bantolomeus** [comment]
Done in https://github.com/Bantolomeus/bookmaster4000mkii/tree/refactor/payload-and-url-refactoring%2379%2381%2390
Please wait with review until #81 and #90 are also done.

**Comment by Husterknupp** [comment]
@Bantolomeus I adopted the UI so that it can handle the payload structure as described in the description. If you wanna keep the `{books: [..]}` structure, I will do another change, but please tell me why

**Comment by Bantolomeus** [comment]
I will change it to `[..]`

**Comment by Bantolomeus** [comment]
> is this still relevant after the discussion in #71 ?
If so, wouldn’t it make sense to keep one endpoint, not create s second one for the same entity, but rather to allow specifying the fields that should be shown in the response?
so GET /books?fields=name
would return
[{name: „Rumo“}, {name: „Warcraft“}]

I would not implement this, but create an issue if it will be relevant in the future.
