### ISSUE TITLE
Endpoint to calculate pages left of a book

### ISSUE THREAD

**Issue by Bantolomeus** [Bantolomeus/bookmaster4000mkii#80]
As a user I would like to know how many pages are left until I finish a certain book, to motivate me further.

- [x] implement GET /books/{book}/pagesLeft

This is part of the book logic and has nothing to do with progress.

**Comment by Bantolomeus** [comment]
Has to be done before #71

**Comment by Husterknupp** [comment]
![image](https://user-images.githubusercontent.com/1265382/48052768-2b7af080-e1a9-11e8-89cf-83acb9afcf35.png)

this is what I can display without this endpoint. Sorry, I think this is not useful for the ui b/c it would add another request per book for no added value. Maybe we should start with a better user story next time. 

@Bantolomeus do you want me to review this anyway.. or will you remove the code? Remember, removed code is bug free code ;-)

What the UI would need is that the `GET /books?progress=..` endpoint returns an object like this `{bookName, currentPage, pagesTotal}`

**Comment by Bantolomeus** [comment]
Looks great. 
I will remove the endpoint. 
I agree that we should start with a user story and define it well to avoid something like that here.
I will implement the endpoint change in #68
