### ISSUE TITLE
Add query param to GET /books

### ISSUE THREAD

**Issue by Bantolomeus** [Bantolomeus/bookmaster4000mkii#81]
As a user I wanna know which books I currently read and which are on my todo list.
For that the query param will help to separat the books into future books, books in reading and finished books.

- [ ] add query param status
- [ ] make it possible to set two values for the search parameter 
- [ ] add new field to bookDTO which contains the book status
- [ ] book status can contain [active, done, remaining]

**Comment by Husterknupp** [comment]
Found this one on SO: https://stackoverflow.com/a/9176496/3592419
Basically there is no canonical way, just a few best practises as long as a uri is unique per resource. This is what they're suggesting for array query params as it is both readable and used by many implementations: `?id[]=101404&id[]=7267261`

AngularJs does it very similar out of the box:
```
Resource.get({status: ['abc', 'def']})

=> GET resource?status=abc&status=def
```

@Bantolomeus can you find out what Spring is mapping the Angular way to? So if you do a post with this status, what is coming out in a Controller?

**Comment by Bantolomeus** [comment]
That helps. 

> @Bantolomeus can you find out what Spring is mapping the Angular way to? So if you do a post with this status, what is coming out in a Controller?

I will check this out for you.

**Comment by Bantolomeus** [comment]
Has to be done after #79

**Comment by Bantolomeus** [comment]
Kotlin extension to handle multiple times the same query param: https://medium.com/@sudomax/getting-query-parameters-in-vert-x-v3-and-kotlin-1b8def1db566
