### ISSUE TITLE
Improve book update

### ISSUE THREAD

**Issue by Bantolomeus** [Bantolomeus/bookmaster4000mkii#88]
As a user I would like to still be able to read the book name during the update process.
current behaviour: 
![image](https://user-images.githubusercontent.com/1318613/48290311-b2162300-e472-11e8-8118-becacee40c85.png)

It would be great if there is a fixed space in the an information field of a book where the input field will appears and does not hide at least the book name.

**Comment by Bantolomeus** [comment]
@Husterknupp what is your opinion about this user story?

**Comment by Husterknupp** [comment]
my first thought was “alter, bist du blind, oder was?”. But thinking about it, maybe you’re not blind but have a very short Kurzzeitgedächtnis. Or why do you forget the book name right after hovering over it?

But sure, I can incorporate a minified version of the bookname into the white overlay or so..

**Comment by Bantolomeus** [comment]
I find it ugly.

**Comment by Bantolomeus** [comment]
But I do not want to lose the autofocus on hover.

**Comment by Bantolomeus** [comment]
It would be enough if the button and field would not be centered but be in the bottom half it.

**Comment by Husterknupp** [comment]
what exactly do you find ugly?

Isn’t the input (how many pages you read) the most important information when you wanna enter how much you read in a particular book today? But as long as you’re only interested in how many pages you’ve read, the input is not very relevant, so why show it unless you actually want to do the input?

**Comment by Bantolomeus** [comment]
I find it feels unnatural that something forces itself on top of the information and make the information unreadable. 
But I want to point out, that it is super handy and I do not want to lose the easy way to update the reading process.
I can also life with it, but I was thinking that maybe we can come up with something that feels more natural. If we can not come up with something we will leave it as it is =)

I may not have expressed myself clear enough, I meant to show the input field at the bottom of the box after one hovers over a book. I do not meant to have the input field there all the time.

**Comment by Husterknupp** [comment]
ok, I start to understand. One more question, why do you hover with your mouse over the book to read the book name? For me it’s two separate things. If I wanna read the book info, I read it without hovering over the card. Only when I wanna do an action (input the progress), I hover over it and then I‘d not be very interested in the other info anymore...

Am 10.11.2018 um 20:17 schrieb Christian Bantel <notifications@github.com<mailto:notifications@github.com>>:


I find it feels unnatural that something forces itself on top of the information and make the information unreadable.
But I want to point out, that it is super handy and I do not want to lose the easy way to update the reading process.
I can also life with it, but I was thinking that maybe we can come up with something that feels more natural. If we can not come up with something we will leave it as it is =)

I may not have expressed myself clear enough, I meant to show the input field at the bottom of the box after one hovers over a book. I do not meant to have the input field there all the time.

**Comment by Bantolomeus** [comment]
I asked another person. I got the same reply you also mentioned, I know on which book I am and do not need the information during the update process. I already agreed to that and I get more and more the feeling we shall let it the way it is on focus on other topics.

**Comment by Bantolomeus** [comment]
@Husterknupp feel free to close this issue. I leave it in your hands.

**Comment by Husterknupp** [comment]
I would also like to focus on different things. Maybe let's try to get all Postman work transferred to a useful UI and then we see how we can make things more intuitive?

**Comment by Bantolomeus** [comment]
Sounds like a plan.
