### ISSUE TITLE
Optional date on book update

### ISSUE THREAD

**Issue by Bantolomeus** [Bantolomeus/bookmaster4000mkii#90]
As a user I would like to have the possibility to set the date of a reading progress myself (update the current page of a book).

It just happened, I was on a trip and wrote down my progress manually and wanted to transfer it into the bookmaster. I had to manipulate the bookUpdates.json file to do so, because I wanted it documented as I really have read it and not 400 pages on one day.

- [x] add optional date to book update 
- [x] use the optional date in the `updateBook` method
- [x] refactor `updateBook`, create more methods to reuse code and make it more readable

If the date is set, then safe the update for this day, add read pages to challenge pages. If there was already an update on this day, then handle the same way as multiple updates on the same day.

**Comment by Bantolomeus** [comment]
@Husterknup This feature breaks the front end, the books under Today can not be seen.

**Comment by Husterknupp** [comment]
doesn’t make much sense. Why would an added field in the update input dto break the UI?

Do you know which payload changed? Or what does the browser console say? Do you see any errors?

**Comment by Bantolomeus** [comment]
![image](https://user-images.githubusercontent.com/1318613/48429242-0835df80-e76d-11e8-8c52-a90ece493450.png)

**Comment by Husterknupp** [comment]
I'm an idiot. You're talking about a feature branch. A note from your side would have been nice that this is on a feature branch though ;-) Now I can reproduce

**Comment by Bantolomeus** [comment]
Sry. I wanted to post that when I got home and then I forgot it =(

**Comment by Husterknupp** [comment]
why does the `GET /books` endpoint return an object not an array? I get `{books: [..]}` which I find boilerplate. Why not simply return `[..]`? Also this is how `$resource` service expects it

**Comment by Husterknupp** [comment]
since you changed it in #79 lets continue the discussion there
