### ISSUE TITLE
Update desktop version

### ISSUE THREAD

**Issue by Bantolomeus** [Bantolomeus/bookmaster4000mkii#91]
As a user I would like to use the newest version of the application with frontend support for easier interaction with the application.

- [x] generate executable jar
- [x] save old files
- [ ] add progress.json
- [ ] call endpoint to sort bookUpdates
- [ ] create batch file to start application
- [ ] execute batch file on pc start

**Comment by Bantolomeus** [comment]
Well I could create the jar but if I try to execute it I always get the error:
`Error: Could not find or load main class com.bantolomeus.Bookmaster4000mkiiApplication`
After one hour of searching for a solution and try and error I will try again another time.

**Comment by Bantolomeus** [comment]
Hmpf, thanks for pointing that out. Now It works on my mac, will test it on windows.

**Comment by Bantolomeus** [comment]
Also works for windows, but the frontend does not start with it.

**Comment by Bantolomeus** [comment]
@Husterknupp didn`t we already had a conversation on how to also start the frontend via the jar? Well, whatever, do you know how to start the frontend via the jar together with the application?

**Comment by Bantolomeus** [comment]
Nice, I only need to have the files (books.json, ect.) in the same folder as the executable jar and they will be used. 
I also wrote the batch file (I use Windows 7), if one is interested how: 
`@echo off
start javaw -jar bookmaster4000mkii-2.0.0.jar`

That way the service is started but the command line window will be closed immediately.

**Comment by Bantolomeus** [comment]
I got an error while executing npm start after npm install on windows. I think the path is wrong, windows uses backslashes instead of slashes and windows can not handle ./
@Husterknupp do you agree to my observation or do you think something else goes wrong? Do you have an idea how to solve this?

Link to screenshot, I could not upload it here:
https://imgur.com/a/sI6T53k

**Comment by Bantolomeus** [comment]
Log: https://imgur.com/5wp06VT

**Comment by Husterknupp** [comment]
the jar includes the UI code. Please have a look into the `pom.xml`to see that scripts are bundled as well. It’s no 🦄 magic 🧙‍♂️ 😉

So running the jar alone (`mvn package` already does the npm shizzle) should already deliver the UI on `localhost:8080/`. If it doesn’t, please open a bug ticket

**Comment by Bantolomeus** [comment]
Wow, you are right. MAGIC!
I will try it out on the desktop pc, but should work.

**Comment by Bantolomeus** [comment]
Well, I tried it out on my desktop pc and it does not work perfectly. It looks like the challenge can not be read, because it says I should read 0 pages per day (that is the default) and I am 0 pages ahead of the plan. Hm, this is also not correct.
I will investigate this, maybe it is a problem of changed names in the files or the files content is not in the correct format.
I will look into it at the weekend and after that I can start #44

**Comment by Bantolomeus** [comment]
And one book is missing. Maybe because it contains a ö in the title.

**Comment by Bantolomeus** [comment]
The missing book is my fault, I used an old backup file without the mentioned book.

**Comment by Bantolomeus** [comment]
The current reading process can not be calculated, because it depends on the progress.json, which does not exists right now on the desktop pc.

**Comment by Bantolomeus** [comment]
I found a bug in the calculation of the current reading progress. I will work on this ticket with a newer version of the application after #44

**Comment by Husterknupp** [comment]
This one confuses me a bit.  Is there still anything that needs to be updated?

**Comment by Bantolomeus** [comment]
no
