### ISSUE TITLE
Integrate SonarCloud into Travis CI

### ISSUE THREAD

**Issue by Bantolomeus** [Bantolomeus/bookmaster4000mkii#98]
As a developer I want to be up to date about the quality of my code to write even better code.

https://docs.travis-ci.com/user/sonarcloud/

**Comment by Husterknupp** [comment]
Kotlin seems to be supported 👍

https://docs.sonarqube.org/plugins/servlet/mobile?contentId=6956158#content/view/1442035

**Comment by Bantolomeus** [comment]
the token name after ``` token: ``` was the problem

**Comment by Bantolomeus** [comment]
sonar scanner is in error: https://travis-ci.org/Bantolomeus/bookmaster4000mkii/builds/469252794

**Comment by Bantolomeus** [comment]
It works =D

**Comment by Bantolomeus** [comment]
looks like the tests do not count towards code coverage =(

**Comment by Husterknupp** [comment]
@Bantolomeus did you already come across the **sonar-kotlin** plugin? Since I’m expecting every language to require sonar to do special things, I googled for „maven kotlin sonar trst coverage“ and found this: https://blog.akquinet.de/2018/07/04/jacoco-and-sonar-with-kotlin/

does that help?

**Comment by Husterknupp** [comment]
@Banto the issue description now contains what should be achieved. Is this what you want or am I missing anything?

**Comment by Bantolomeus** [comment]
Yes thanks. I did not add a description, because ones it works all these stuff would be fulfilled automatically and I am lazy and did not needed the description. The task is self explaining, that is at least my opinion. Well the story description is missing. I will add it.

**Comment by Bantolomeus** [comment]
Well, now with the story description the reason for this issue is clear.

**Comment by Bantolomeus** [comment]
@Husterknupp thanks for the blog post. I will integrate the needed stuff.

**Comment by Husterknupp** [comment]
I would like to have a CI system for the bookmaster. Is this issue the right place? 
(Since it's more specifically talking about SonarCube)

GitHub workflow actions provide everything we need I think. No need for Travis any longer

**Comment by Husterknupp** [comment]
@Bantolomeus I created #113 for the general CI tasks
